### ISSUE TITLE
Question: is there an easy way to set column width?

### ISSUE THREAD

**Issue by paulvanbladel** [NonFactors/MVC6.Grid#163]

**Comment by Muchiachio** [comment]
Not sure what is considered easy, but with css classes it's `.Css("action-column")`.
```CSS
.action-column {
    width: 36px;
}
```
