### ISSUE TITLE
how to use materilizecss font icons and overwrite classes

### ISSUE THREAD

**Issue by sajadghobadi** [NonFactors/MVC6.Grid#208]

**Comment by Muchiachio** [comment]
Usually overriding content with correct icon code is enough.
```CSS
.mvc-grid-filter::before {
    font-family: '<material_font>';
    content: '<material_icon_code>';
}
```
