### ISSUE TITLE
Filtering goes away if you apply CSS to a column

### ISSUE THREAD

**Issue by tkappeler** [NonFactors/MVC6.Grid#22]
I am adding .CSS("col-sm-3") to a column definition and also setting Filterable to the grid.  The Filtering for the column with the extra CSS is not displayed and not enabled.  if I remove the CSS, I gain back the filtering but the column is very long.

**Comment by Muchiachio** [comment]
This happens, because bootstrap's `col-sm-3` class not only adds width, but also adds unneeded positioning information which disposition grid filter. Here is the offending styling
```CSS
table th[class*="col-"] {
  position: static;
}
```
Until I improve compatibility with these bootstrap classes, you can add this override in your css
```CSS
.mvc-grid .filterable {
    position: relative;
}
```
