### ISSUE TITLE
Pagination Styling

### ISSUE THREAD

**Issue by amkuchta** [NonFactors/MVC6.Grid#49]
As it stands, my page selectors at the bottom of the grid are unstyled - looking through the code / CSS within the repository, there are no styles set for the following classes:

- mvc-grid-pager
- mvc-grid-pager-rows
- pagination

Is this by default?

**Comment by Muchiachio** [comment]
Yes, it's by default. I didn't want to include bootstrap/foundation/semantic or any other css framework as a project dependency for that. I guess I should at least add default styling so it looks decent without it.
What do you think?

**Comment by amkuchta** [comment]
I think having  some default would be acceptable - the styling on the Paging demo is perfect, in my opinion.  Others can modify / override as they see fit.

Any chance that you could provide me with the CSS used for the demo prior to the new release?  I'd like to go ahead and add it in to my application.

**Comment by Muchiachio** [comment]
This is what I managed to extract from bootstrap, could be shortened by a lot.
```CSS
ul {
    margin-top: 0px;
    margin-bottom: 10px;
}

.pagination {
    display: inline-block;
    padding-left: 0px;
    margin: 20px 0px;
    border-radius: 4px;
}

    .pagination > li {
        display: inline;
    }

        .pagination > li > span {
            position: relative;
            float: left;
            padding: 6px 12px;
            margin-left: -1px;
            line-height: 1.42857;
            color: #337ab7;
            text-decoration: none;
            background-color: #fff;
            border: 1px solid #ddd;
        }

        .pagination > li:first-child > span {
            margin-left: 0px;
            border-top-left-radius: 4px;
            border-bottom-left-radius: 4px;
        }

        .pagination > li:last-child > span {
            border-top-right-radius: 4px;
            border-bottom-right-radius: 4px;
        }

        .pagination > li > span:hover {
            z-index: 3;
            color: #23527c;
            background-color: #eee;
            border-color: #ddd;
        }

    .pagination > .active > span, .pagination > .active > span:hover {
        z-index: 2;
        color: #fff;
        cursor: default;
        background-color: #337ab7;
        border-color: #337ab7;
    }

    .pagination > .disabled > span, .pagination > .disabled > span:hover {
        color: #777;
        cursor: not-allowed;
        background-color: #fff;
        border-color: #ddd;
    }

.mvc-grid-pager li {
    cursor: pointer;
}

.mvc-grid-pager {
    box-sizing: border-box;
    text-align: center;
}

    .mvc-grid-pager * {
        box-sizing: border-box;
    }

.pagination {
    margin-bottom: 0px;
}

    .pagination > li > span, .pagination > .disabled > span {
        background: rgba(255, 255, 255, 0.54902);
    }

        .pagination > .disabled > span:hover {
            background-color: #eee;
            border-color: #ddd;
            color: #23527c;
        }

    .pagination > .active > span {
        background: #82a1d2;
        border-color: #83aed3;
    }
```
